package com.chaemil.hgms.model;

public enum RequestType {
    GET_PHOTO_ALBUM, SEARCH, GET_HOMEPAGE, GET_LIVESTREAM, POST_ANALYTICS_ALIVE, POST_VIDEO_VIEW, GET_CATEGORIES, GET_VIDEO, GET_SONGS, GET_ARCHIVE

}
